/*!CK:4104602460!*//*1455658939,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["drMj9"]); }

__d('concatMap',[],function a(b,c,d,e,f,g){if(c.__markCompiled)c.__markCompiled();function h(i,j){var k=-1,l=j.length,m=[],n=undefined;while(++k<l){n=i(j[k],k,j);if(Array.isArray(n)){Array.prototype.push.apply(m,n);}else Array.prototype.push.call(m,n);}return m;}f.exports=h;},null);
__d('StringTrims',[],function a(b,c,d,e,f,g){if(c.__markCompiled)c.__markCompiled();var h={trimLeft:function(i){return i.replace(/^\s+/,'');},trimRight:function(i){return i.replace(/\s+$/,'');}};f.exports=h;},null);
__d('LitestandEllipsis',['DOMQuery','StringTrims','concatMap','getElementText','isTextNode'],function a(b,c,d,e,f,g,h,i,j,k,l){if(c.__markCompiled)c.__markCompiled();var m,n={add:function(q,r,s){s=s||q;h.scry(q,'br').forEach(function(z){z.parentNode&&z.parentNode.removeChild(z);});var t=s.offsetHeight||0;if(t<=r)return q;var u,v='\u2026',w=p(q),x=w.length-1,y=k(w[x]);if(x===0)y=i.trimLeft(y);while(x>=0&&t>r){u=Math.max(y.lastIndexOf(' '),y.lastIndexOf('\n'));if(u===-1)u=y.length-v.length-1;if(u<=0){o(w[x],'');x--;y=k(w[x]);}else{y=i.trimRight(y.substr(0,u))+v;o(w[x],y);}t=(s.offsetHeight||0)-1;}}};function o(q,r){m=m||(q.textContent!=null?'textContent':'innerText');q[m]=r;}function p(q){if(l(q))return [q];return j(p,Array.from(q.childNodes));}f.exports=n;},null);
__d('queryThenMutateDOM',['Run','emptyFunction','requestAnimationFrame'],function a(b,c,d,e,f,g,h,i,j){if(c.__markCompiled)c.__markCompiled();var k,l,m={},n=[],o=[];function p(s,t,u){if(!s&&!t)return;if(u&&m.hasOwnProperty(u)){return;}else if(u)m[u]=1;n.push(t||i);o.push(s||i);r();if(!k){k=true;h.onLeave(function(){k=false;l=false;m={};n.length=0;o.length=0;});}}p.prepare=function(s,t,u){return function(){for(var v=arguments.length,w=Array(v),x=0;x<v;x++)w[x]=arguments[x];w.unshift(this);var y=Function.prototype.bind.apply(s,w),z=t.bind(this);p(y,z,u);};};function q(){m={};var s=o.length,t=n.length,u=[],v;while(s--){v=o.shift();u.push(v());}while(t--){v=n.shift();v(u.shift());}l=false;r();}function r(){if(!l&&(o.length||n.length)){l=true;j(q);}}f.exports=p;},null);
__d('LitestandShareAttachment',['CSS','DOMQuery','LitestandEllipsis','LitestandShareAttachmentConfig','csx','cx','queryThenMutateDOM'],function a(b,c,d,e,f,g,h,i,j,k,l,m,n){if(c.__markCompiled)c.__markCompiled();var o=16,p=22,q=20,r=5,s=3,t=2,u=2,v=5,w=5,x="_5qqr",y="_6m2",z={getSimpleCropClass:function(){return x;},_truncateText:function(da,ea){var fa,ga,ha,ia=aa(da);n(function(){fa=i.scry(da,"._6m6")[0];ga=i.scry(da,"._6m7")[0];ha=ba(da,fa,ia);},function(){if(!da.offsetHeight){if(ea)h.addClass(da,x);return;}if(!ha){ga&&h.hide(ga);fa&&j.add(fa,ia*ca(da));}else if(ga&&ha){h.show(ga);j.add(ga,ha*o);}});},init:function(da){if(h.hasClass(da,x)){var ea=false;n(function(){if(da.offsetHeight)ea=true;},(function(){if(ea){h.removeClass(da,x);this._truncateText(da,true);}}).bind(this));return;}else{var fa=k.ALLOW_SIMPLE_CROP&&h.hasClass(da,y);this._truncateText(da,fa);}},getNumDescriptionLines:function(da){return ba(da,i.scry(da,"._6m6")[0],aa(da));},getDescriptionLineHeight:function(){return o;}};function aa(da){var ea=h.hasClass(da,"_59ap"),fa=h.hasClass(da,"_pb2"),ga=i.scry(da,"^div._4rtc").length>0,ha;if(fa){ha=u;}else if(ga){ha=t;}else if(ea){ha=s;}else ha=r;return ha;}function ba(da,ea,fa){var ga=i.scry(da,"._6m3")[0];if(!ea||!ga)return 0;var ha=i.scry(da,"._59tj")[0],ia=h.hasClass(da,"_59ap"),ja=h.hasClass(da,"_pb2"),ka=Math.round(ea.scrollHeight/ca(da));if(ka>fa&&!ja)return 0;var la=ga.offsetHeight-v-ea.offsetHeight-(ha?ha.offsetHeight:0)-(ia?0:w)+1;return Math.floor(Math.max(la,0)/o);}function ca(da){return h.hasClass(da,"_pb2")?q:p;}f.exports=z;},null);
__d('VideoDisplayTimePlayButton',['CSS','DataStore','Event'],function a(b,c,d,e,f,g,h,i,j){if(c.__markCompiled)c.__markCompiled();var k={},l='_spinner',m={getClicked:function(n){return i.get(n,'clicked',false);},register:function(n,o){var p=n.id;k[p]=j.listen(n,'click',function(){if(o){h.hide(n);h.show(o);}i.set(n,'clicked',true);});if(o)k[p+l]=j.listen(o,'click',function(){h.hide(o);h.show(n);i.set(n,'clicked',false);});},unregister:function(n){var o=n.id;if(k.hasOwnProperty(o))k[o].remove();var p=o+l;if(k.hasOwnProperty(p))k[p].remove();}};f.exports=m;},null);
__d('VideosRenderingInstrumentation',['DataStore','VideoPlayerHTML5Experiments','performanceAbsoluteNow'],function a(b,c,d,e,f,g,h,i,j){if(c.__markCompiled)c.__markCompiled();var k={storeRenderTime:function(l){var m=i.useMonotonicallyIncreasingTimers?j():Date.now();h.set(l,'videos_rendering_instrumentation',m);return m;},retrieveRenderTime:function(l){var m=h.get(l,'videos_rendering_instrumentation',NaN);if(Number.isNaN(m))m=k.storeRenderTime(l);return m;}};f.exports=k;},null);